trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: |
    chmod u+x ./deploy.sh
    ./deploy.sh
  workingDirectory: 'labs/flixtube/azure-deploy'
  env:
    VERSION: $(BuildId)
    ARM_CLIENT_ID: $(ARM_CLIENT_ID)
    ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
    ARM_TENANT_ID: $(ARM_TENANT_ID)
    ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
    STORAGE_ACCOUNT_NAME: $(STORAGE_ACCOUNT_NAME)
    STORAGE_ACCESS_KEY: $(STORAGE_ACCESS_KEY)
